# fly.toml app configuration file generated for new-mint-tea-bot on 2023-06-15T08:40:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "new-mint-tea-bot"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
